Repository identitatem/idp-mgmt-operator, pull requests merged in 2021-09, with the labels that each got.

#34 Clean deployment
  config/manager-coverage/manager-coverage.yaml
  config/manager/manager.yaml
  controllers/authrealm/authrealm_controller.go
  controllers/authrealm/strategy.go
  deploy/idp-strategy-operator/manager.yaml
  deploy/idp-strategy-operator/role.yaml
  deploy/idp-strategy-operator/role_binding.yaml
  deploy/idp-strategy-operator/service_account.yaml
  deploy/resources.go
Labels: approved, lgtm, dco-signoff: yes

#35 a few tweaks
  controllers/authrealm/dex.go
  controllers/clusteroauth/suite_test.go
Labels: approved, lgtm, dco-signoff: yes

#37 fix sonar random issue
  controllers/placementdecision/common.go
  controllers/strategy/strategy_controller.go
  pkg/helpers/random.go
Labels: approved, lgtm, dco-signoff: yes

#38 fix for sonar
  pkg/helpers/random.go
Labels: approved, lgtm, dco-signoff: yes

#36 Create Clusteroauth
  config/manager/manager.yaml
  controllers/authrealm/authrealm_controller.go
  controllers/authrealm/dex.go
  controllers/authrealm/strategy.go
  controllers/authrealm/suite_test.go
  controllers/clusteroauth/clusteroauth_controller.go
  controllers/clusteroauth/suite_test.go
  controllers/placementdecision/backplane_strategy.go
  controllers/placementdecision/common.go
  controllers/placementdecision/placementdecision_controller.go
  controllers/placementdecision/suite_test.go
  controllers/strategy/strategy_controller.go
  controllers/strategy/suite_test.go
  pkg/fake/tmp.go
  pkg/fake/tmp_test.go
  pkg/helpers/common.go
  pkg/helpers/infratructure.go
  pkg/helpers/names.go
Labels: approved, dco-signoff: no

#39 Add aggregated role
  config/manager/manager.yaml
  config/rbac/role-aggregated-clusterrole.yaml
  config/rbac/role.yaml
  controllers/authrealm/authrealm_controller.go
  controllers/authrealm/dex.go
  controllers/authrealm/suite_test.go
  controllers/clusteroauth/clusteroauth_controller.go
  controllers/clusteroauth/suite_test.go
  deploy/dex-operator/leader_election_role.yaml
  deploy/dex-operator/leader_election_role_binding.yaml
  deploy/dex-operator/leader_election_role_old.yaml
  go.mod
  go.sum
Labels: approved, lgtm, dco-signoff: yes

#41 Use Leader role from dex-operator
  controllers/authrealm/suite_test.go
  controllers/authrealm/templatefunction.go
  controllers/placementdecision/common.go
  deploy/dex-operator/leader_election_role.yaml
  deploy/dex-operator/leader_election_role_old.yaml
  deploy/dex-operator/role.yaml
  go.mod
  go.sum
Labels: approved, lgtm, dco-signoff: yes

#42 Delete clusteroauth
  controllers/placementdecision/common.go
  controllers/placementdecision/placementdecision_controller.go
  test/functional/controller_test.go
Labels: approved, lgtm, dco-signoff: yes

#43 Update readme, change dex image env var
  README.md
  config/manager-coverage/manager-coverage.yaml
  config/manager/manager.yaml
  controllers/authrealm/dex.go
Labels: approved, lgtm, dco-signoff: yes

#44 update dexclient and dexserver
  README.md
  controllers/authrealm/dex.go
  controllers/authrealm/suite_test.go
  controllers/clusteroauth/clusteroauth_controller.go
  controllers/placementdecision/common.go
  controllers/placementdecision/placementdecision_controller.go
  controllers/placementdecision/suite_test.go
  deploy/dex-operator/leader_election_role.yaml
  deploy/dex-operator/leader_election_role_binding.yaml
  deploy/dex-operator/manager.yaml
  deploy/dex-operator/namespace.yaml
  deploy/dex-operator/role_binding.yaml
  deploy/dex-operator/service_account.yaml
  pkg/helpers/names.go
  test/functional/controller_test.go
Labels: approved, lgtm, dco-signoff: yes

#45 Split dex-operator and dex-server
  controllers/authrealm/authrealm_controller.go
  controllers/authrealm/dex.go
  controllers/authrealm/suite_test.go
  controllers/authrealm/templatefunction.go
  controllers/placementdecision/common.go
  controllers/placementdecision/placementdecision_controller.go
  controllers/placementdecision/suite_test.go
  deploy/dex-operator/leader_election_role.yaml
  deploy/dex-operator/leader_election_role_binding.yaml
  deploy/dex-operator/manager.yaml
  deploy/dex-operator/namespace.yaml
  deploy/dex-operator/role.yaml
  deploy/dex-operator/role_binding.yaml
  deploy/dex-operator/service_account.yaml
  go.mod
  go.sum
  pkg/helpers/names.go
  test/functional/controller_test.go
Labels: approved, lgtm, dco-signoff: yes

#46 Implement dex-operator deletion
  controllers/authrealm/authrealm_controller.go
  controllers/authrealm/dex.go
  controllers/clusteroauth/clusteroauth_controller.go
  controllers/placementdecision/backplane_strategy.go
  controllers/placementdecision/common.go
  controllers/placementdecision/dex.go
  controllers/placementdecision/placementdecision_controller.go
  pkg/helpers/finilzers.go
  test/functional/controller_test.go
Labels: approved, lgtm, dco-signoff: yes

#49 Watch dexclient and dexserver
  config/rbac/role.yaml
  controllers/authrealm/authrealm_controller.go
  controllers/authrealm/dex.go
  controllers/authrealm/rhsso.go
  controllers/authrealm/strategy.go
  controllers/authrealm/suite_test.go
  controllers/placementdecision/common.go
  controllers/placementdecision/dex.go
  controllers/placementdecision/placementdecision_controller.go
  controllers/placementdecision/suite_test.go
  controllers/strategy/backplane_strategy.go
  controllers/strategy/grc_strategy.go
  controllers/strategy/strategy_controller.go
  controllers/strategy/suite_test.go
  go.mod
  go.sum
  pkg/helpers/common.go
  pkg/helpers/finilzers.go
  pkg/helpers/names.go
  test/functional/controller_test.go
Labels: approved, lgtm, dco-signoff: yes

#48 use branch name for image tag
  Makefile
Labels: approved, lgtm, dco-signoff: no

#51 webhook dom
  Dockerfile
  Dockerfile-coverage
  Makefile
  cmd/manager/main.go
  cmd/manager/main_test.go
  cmd/webhook/main.go
  config/default/kustomization.yaml
  config/manager-coverage/manager-coverage.yaml
  config/manager/manager.yaml
  config/rbac/role.yaml
  config/webhook/kustomization.yaml
  config/webhook/service.yaml
  config/webhook/webhook-apiservice.yaml
  config/webhook/webhook-clusterrole.yaml
  config/webhook/webhook-clusterrolebinding.yaml
  config/webhook/webhook-service.yaml
  config/webhook/webhook-validating-config.yaml
  config/webhook/webhook.yaml
  controllers/authrealm/authrealm_controller.go
  controllers/authrealm/dex.go
  controllers/placementdecision/dex.go
  controllers/placementdecision/suite_test.go
  go.mod
  go.sum
  main.go
  main_test.go
  test/functional/controller_test.go
  webhook/authrealm_webhook.go
Labels: approved, lgtm, dco-signoff: yes

#52 Fix timeout webhook
  Makefile
  build/run-functional-tests.sh
  config/default/kustomization.yaml
  config/manager-coverage/kustomization.yaml
  config/manager/kustomization.yaml
  config/manager/manager.yaml
  config/webhook/kustomization.yaml
  config/webhook/service_account.yaml
  config/webhook/webhook.yaml
  config/webhook/webhook_apiservice.yaml
  config/webhook/webhook_clusterrole.yaml
  config/webhook/webhook_clusterrolebinding.yaml
  config/webhook/webhook_service.yaml
  config/webhook/webhook_validating_config.yaml
Labels: approved, lgtm, dco-signoff: yes

#53 fix webhook update
  webhook/authrealm_webhook.go
Labels: approved, lgtm, dco-signoff: yes

#54 Add RELATED_IMAGE_DEX
  config/manager/kustomization.yaml
  deploy/dex-operator/manager.yaml
  go.mod
  go.sum
Labels: approved, lgtm, dco-signoff: yes

#55 update routeSubDomain
  config/manager-coverage/kustomization.yaml
  controllers/strategy/suite_test.go
  go.mod
  go.sum
  test/config/example/github-authrealm.yaml
  webhook/authrealm_webhook.go
Labels: approved, lgtm, dco-signoff: yes

#56 Fix issuer url
  config/manager-coverage/kustomization.yaml
  config/manager/kustomization.yaml
  controllers/placementdecision/common.go
Labels: approved, lgtm, dco-signoff: yes

#57 Authrealm script
  Makefile
  hack/generate-cr.sh
  webhook/authrealm_webhook_test.go
Labels: approved, lgtm, dco-signoff: no

#60 Add logs to clusteroauth_controller
  config/manager/manager.yaml
  controllers/clusteroauth/clusteroauth_controller.go
Labels: approved, lgtm, dco-signoff: yes

#62 temp. pin dex-operator to working version
  config/manager/manager.yaml
Labels: approved, lgtm, dco-signoff: yes

#61 Fix connectors
  config/manager/manager.yaml
  controllers/authrealm/dex.go
  controllers/authrealm/suite_test.go
  go.mod
  go.sum
  hack/generate-cr.sh
Labels: approved, lgtm, dco-signoff: yes

#64 Change dexclient url
  controllers/clusteroauth/clusteroauth_controller.go
  controllers/clusteroauth/suite_test.go
  controllers/placementdecision/common.go
  controllers/placementdecision/dex.go
Labels: approved, lgtm, dco-signoff: yes

#63 fix readme
  README.md
Labels: approved, lgtm, dco-signoff: yes

#65 add claims to clusteroauth
  README.md
  controllers/placementdecision/common.go
  controllers/placementdecision/dex.go
  controllers/placementdecision/placementdecision_controller.go
  hack/generate-cr.sh
Labels: approved, do-not-merge/hold, dco-signoff: no
