Repository identitatem/idp-mgmt-operator, pull requests merged in 2021-07, with the labels that each got.

#4 Add component files
  COMPONENT_NAME
  COMPONENT_VERSION
Labels: approved, lgtm

#6 add prow targets
  Makefile
Labels: approved, lgtm

#7 Functional test
  .copyrightignore
  .github/workflows/functional-tests.yml
  .gitignore
  Makefile
  README.md
  api/authrealm/v1/authrealm_types.go
  api/authrealm/v1/groupversion_info.go
  api/authrealm/v1/zz_generated.deepcopy.go
  build/check-copyright.sh
  build/copyright-header.txt
  build/run-functional-tests-clean.sh
  build/run-functional-tests.sh
  config/crd/bases/identitatem.io_authrealms.yaml
  config/default/kustomization.yaml
  config/manager/kustomization.yaml
  controllers/authrealm_controller.go
  controllers/suite_test.go
  go.mod
  go.sum
  hack/boilerplate.go.txt
  hack/update-codegen.sh
  hack/verify-codegen.sh
  main.go
  pkg/fake/tmp.go
  pkg/fake/tmp_test.go
  test/functional/controller_suite_test.go
  test/functional/controller_test.go
Labels: approved, lgtm

#8 add initial sonar prop file
  .github/workflows/functional-tests.yml
  sonar-project.properties
Labels: approved, lgtm

#10 cleaning open-cluster-management
  .github/workflows/functional-tests.yml
  build/bin/coverage-entrypoint-func.sh
Labels: approved, lgtm

#11 Build changes
  .copyrightignore
  api/authrealm/v1/doc.go
  dependencymagnet/doc.go
  test/functional/controller_suite_test.go
  test/functional/controller_test.go
Labels: approved, lgtm

#14 trigger build - test prow
  .triggerbuild
Labels: approved, dco-signoff: yes, lgtm

#15 trigger build - test fast forward
  .triggerbuild
Labels: approved, dco-signoff: yes

#16 Api suite test
  Makefile
  api/authrealm_suite_test.go
  api/identityprovider_suite_test.go
  api/suite_test.go
  config/samples/identitatem.io_v1_authrealm.yaml
  config/samples/identitatem.io_v1alpha1_authrealm.yaml
  config/samples/identitatem.io_v1alpha1_identityprovider.yaml
  go.mod
  go.sum
Labels: approved, dco-signoff: yes, lgtm
