Repository identitatem/idp-mgmt-operator, pull requests merged in 2022-01, with the labels that each got.

#146 update Dockerfile for ACM git org change to stolostron
  Dockerfile
Labels: approved, lgtm, dco-signoff: yes

#147 Add doc on how installer works
  CONTRIBUTING.md
Labels: approved, lgtm, dco-signoff: yes

#149 Add prereq ACM/MCE
  CONTRIBUTING.md
  config/rbac/role.yaml
  controllers/installer/installer_controller.go
  deploy/idp-mgmt-operator/clusterrole.yaml
  test/functional/controller_suite_test.go
Labels: approved, lgtm, dco-signoff: yes

#151 rectify copy paste error from generate cr script
  hack/generate-cr.sh
Labels: approved, lgtm, dco-signoff: yes

#150 add delete propagation policy to idp-oauth manifestwork
  controllers/clusteroauth/clusteroauth_controller.go
Labels: approved, lgtm, dco-signoff: yes

#152 add e2e skeleton test scripts
  build/cluster-clean-up.sh
  build/run-e2e-tests.sh
Labels: approved, lgtm, dco-signoff: yes

#153 migrate to stolostron
  CONTRIBUTING.md
  Dockerfile
  MISSION.md
  README.md
  controllers/authrealm/authrealm_controller.go
  controllers/clusteroauth/clusteroauth_controller.go
  controllers/clusteroauth/suite_test.go
  controllers/installer/installer_controller.go
  controllers/strategy/strategy_controller.go
  go.mod
  go.sum
  test/functional/controller_suite_test.go
  test/functional/controller_test.go
Labels: approved, lgtm, dco-signoff: yes

#154 Prow e2e b
  CONTRIBUTING.md
  Dockerfile
  Dockerfile.cypress
  MISSION.md
  Makefile
  README.md
  controllers/authrealm/authrealm_controller.go
  controllers/clusteroauth/clusteroauth_controller.go
  controllers/clusteroauth/suite_test.go
  controllers/installer/installer_controller.go
  controllers/strategy/strategy_controller.go
  go.mod
  go.sum
  test/e2e/download-clis.sh
  test/e2e/run-prow-e2e.sh
  test/e2e/start-cypress-tests.sh
  test/functional/controller_suite_test.go
  test/functional/controller_test.go
Labels: lgtm, dco-signoff: yes

#156 some 0.2.0 changes for CSV
  .github/workflows/publish.yml
  COMPONENT_VERSION
  Makefile
  README.md
  bundle/manifests/idp-mgmt-operator.clusterserviceversion.yaml
  config/manifests/bases/idp-mgmt-operator.clusterserviceversion.yaml
Labels: approved, lgtm, dco-signoff: yes

#155 process for upgrade
  .gitignore
  Makefile
  README.md
  config/manifests/bases/idp-mgmt-operator.clusterserviceversion.yaml
Labels: approved, lgtm, dco-signoff: yes

#157 0.2.0 RC1
  README.md
  bundle/manifests/idp-mgmt-operator.clusterserviceversion.yaml
  config/installer/installer.yaml
  go.mod
  go.sum
Labels: approved, lgtm, dco-signoff: yes

#160 Release process
  RELEASE.md
Labels: approved, lgtm, dco-signoff: yes

#159 testing out e2e prow
  test/e2e/install-signed-cert.sh
  test/e2e/run-prow-e2e.sh
  test/e2e/start-cypress-tests.sh
Labels: lgtm, dco-signoff: yes

#162 Change how MCE/ACM are detected
  config/rbac/role.yaml
  controllers/installer/installer_controller.go
  deploy/idp-mgmt-operator/clusterrole.yaml
  test/config/crd/external/mce_crd.yaml
  test/functional/controller_suite_test.go
Labels: approved, lgtm, dco-signoff: yes

#163 Update csv with new role
  bundle/manifests/idp-mgmt-operator.clusterserviceversion.yaml
Labels: approved, lgtm, dco-signoff: yes

#164 Restore originnal image and version
  bundle/manifests/idp-mgmt-operator.clusterserviceversion.yaml
Labels: approved, lgtm, dco-signoff: yes

#167 Ginkgo E2E tests
  .copyrightignore
  .gitignore
  Makefile
  test/e2e/README.md
  test/e2e/idp_mgmt_for_github.go
  test/e2e/idp_mgmt_suite_test.go
  test/e2e/testdata/github-authrealm.yaml
  test/e2e/utils/utils.go
Labels: lgtm, dco-signoff: yes

#170 Updates to E2E specs for GitHub authrealm
  test/e2e/idp_mgmt_for_github_test.go
  test/e2e/utils/utils.go
Labels: lgtm, dco-signoff: yes

#168 wire in ginkgo e2e tests
  Dockerfile.cypress
  test/e2e/README.md
  test/e2e/install-IDP.sh
  test/e2e/run-ginkgo-e2e-tests.sh
  test/e2e/run-prow-e2e.sh
  test/e2e/testdata/github-authrealm.yaml
  test/e2e/utils/utils.go
Labels: lgtm, dco-signoff: no

#172 Test - For moving over the E2E tests from test branch to main branch
  .copyrightignore
  .gitignore
  Dockerfile.cypress
  Makefile
  test/e2e/README.md
  test/e2e/download-clis.sh
  test/e2e/idp_mgmt_for_github_test.go
  test/e2e/idp_mgmt_suite_test.go
  test/e2e/install-IDP.sh
  test/e2e/install-signed-cert.sh
  test/e2e/run-ginkgo-e2e-tests.sh
  test/e2e/run-prow-e2e.sh
  test/e2e/setup-go.sh
  test/e2e/start-cypress-tests.sh
  test/e2e/testdata/github-authrealm.yaml
  test/e2e/utils/utils.go
Labels: approved, lgtm, do-not-merge/hold, dco-signoff: no

#176 upgrade packages version
  Dockerfile
  Makefile
  PROJECT
  README.md
  build/run-functional-tests.sh
  bundle.Dockerfile
  bundle/manifests/idp-mgmt-operator.clusterserviceversion.yaml
  bundle/metadata/annotations.yaml
  config/installer-coverage/kustomization.yaml
  config/installer/kustomization.yaml
  config/rbac/role.yaml
  controllers/authrealm/suite_test.go
  controllers/clusteroauth/suite_test.go
  controllers/placementdecision/suite_test.go
  controllers/strategy/suite_test.go
  deploy/webhook/webhook.yaml
  go.mod
  go.sum
  test/functional/controller_suite_test.go
  test/functional/controller_test.go
  webhook/authrealm_webhook_test.go
  webhook/suite_test.go
Labels: approved, lgtm, dco-signoff: yes

#169 add openid connector support
  controllers/authrealm/dex.go
  controllers/authrealm/suite_test.go
  controllers/placementdecision/dex.go
Labels: approved, lgtm, dco-signoff: yes

#181 update copyright check for js
  build/check-copyright.sh
Labels: approved, lgtm, dco-signoff: yes
